

name: API Test Demo Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 00 4 * * *
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -Dsuite=suite -X
      
    - name: Generate Allure Report
      run: mvn allure:report
      
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results/
        
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with:
        name: logs
        path: logs/
        
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.8
      with:
        allure_results: target/allure-results
        allure_report: target/allure-report
        allure_history: allure-history
        
    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven-plugin/ 
  
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/allure-report

  




        
